[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "flashduty_sdk"
version = "0.1.0"
requires-python = ">=3.9"

[tool.maturin]
features = ["python"]
python-source = "python"
module-name = "flashduty_sdk.flashduty_sdk"
